### ISSUE TITLE
Unable to reproduce examples

### ISSUE THREAD

**Issue by DhanshreeA** [nielsvanspauwen/pystructurizr#1]
Hi, fantastic work! I am trying to run the examples in the repository. For example, I am trying to dump the Structurizr DSL for chatserver components view by running the following command, however it is currently crashing:
```
pystructurizr dev --view example.chatserver_componentview
```

Here's the stacktrace:

```python
Setting up live preview of view example.chatserver_componentview...
Generating diagram...
Traceback (most recent call last):
  File "/home/dee/.pyenv/versions/3.8.14/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/dee/.pyenv/versions/3.8.14/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/dee/learn_xyz/learn_structurizr/pystructurizr/pystructurizr/cli.py", line 96, in <module>
    cli()
  File "/home/dee/.pyenv/versions/3.8.14/envs/pystructurizr/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/dee/.pyenv/versions/3.8.14/envs/pystructurizr/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/dee/.pyenv/versions/3.8.14/envs/pystructurizr/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dee/.pyenv/versions/3.8.14/envs/pystructurizr/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dee/.pyenv/versions/3.8.14/envs/pystructurizr/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/dee/learn_xyz/learn_structurizr/pystructurizr/pystructurizr/cli.py", line 21, in dump
    diagram_code, imported_modules = generate_diagram_code(view)
  File "/home/dee/learn_xyz/learn_structurizr/pystructurizr/pystructurizr/cli_helper.py", line 15, in generate_diagram_code
    module = importlib.import_module(view)
  File "/home/dee/.pyenv/versions/3.8.14/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/dee/learn_xyz/learn_structurizr/pystructurizr/example/chatserver_componentview.py", line 1, in <module>
    from example.workspace import workspace
  File "/home/dee/learn_xyz/learn_structurizr/pystructurizr/example/workspace.py", line 1, in <module>
    from pystructurizr.dsl import Workspace
  File "/home/dee/learn_xyz/learn_structurizr/pystructurizr/pystructurizr/dsl.py", line 255, in <module>
    class Style:
  File "/home/dee/learn_xyz/learn_structurizr/pystructurizr/pystructurizr/dsl.py", line 256, in Style
    def __init__(self, style_map: dict[str, str]):
TypeError: 'type' object is not subscriptable
Traceback (most recent call last):
  File "/home/dee/.pyenv/versions/pystructurizr/bin/pystructurizr", line 8, in <module>
    sys.exit(cli())
  File "/home/dee/.pyenv/versions/3.8.14/envs/pystructurizr/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/dee/.pyenv/versions/3.8.14/envs/pystructurizr/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/dee/.pyenv/versions/3.8.14/envs/pystructurizr/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dee/.pyenv/versions/3.8.14/envs/pystructurizr/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dee/.pyenv/versions/3.8.14/envs/pystructurizr/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/dee/.pyenv/versions/3.8.14/envs/pystructurizr/lib/python3.8/site-packages/pystructurizr/cli.py", line 56, in dev
    asyncio.run(observe_loop())
  File "/home/dee/.pyenv/versions/3.8.14/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/dee/.pyenv/versions/3.8.14/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/dee/.pyenv/versions/3.8.14/envs/pystructurizr/lib/python3.8/site-packages/pystructurizr/cli.py", line 50, in observe_loop
    modules_to_watch = await async_behavior()
  File "/home/dee/.pyenv/versions/3.8.14/envs/pystructurizr/lib/python3.8/site-packages/pystructurizr/cli.py", line 45, in async_behavior
    result = generate_diagram_code_in_child_process(view)
  File "/home/dee/.pyenv/versions/3.8.14/envs/pystructurizr/lib/python3.8/site-packages/pystructurizr/cli_helper.py", line 34, in generate_diagram_code_in_child_process
    child_output = run_child_process()
  File "/home/dee/.pyenv/versions/3.8.14/envs/pystructurizr/lib/python3.8/site-packages/pystructurizr/cli_helper.py", line 30, in run_child_process
    output = subprocess.check_output([sys.executable, "-m", "pystructurizr.cli", "dump", "--as-json", "--view", view])
  File "/home/dee/.pyenv/versions/3.8.14/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/dee/.pyenv/versions/3.8.14/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/dee/.pyenv/versions/3.8.14/envs/pystructurizr/bin/python3.8', '-m', 'pystructurizr.cli', 'dump', '--as-json', '--view', 'example.chatserver_componentview']' returned non-zero exit status 1.
```

For reference, I am running pystructurizr in Python version 3.8.14.

**Comment by DhanshreeA** [comment]
I've created a PR to fix this: https://github.com/nielsvanspauwen/pystructurizr/pull/2. I'm also able to run the examples now. Thanks for the work!

**Comment by nielsvanspauwen** [comment]
Thank you for your contribution!
